### PR TITLE
fix(comp: tabs): error style when nesting tabs

### LINKED ISSUE #913: [comp:tabs] tabs嵌套时 内层的tabs的type失效
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/nervous-murdock-9y35xr?file=/src/Demo.vue](https://codesandbox.io/s/nervous-murdock-9y35xr?file=/src/Demo.vue)

### Steps to reproduce
https://codesandbox.io/s/nervous-murdock-9y35xr?file=/src/Demo.vue

### What is expected?
type能生效

### What is actually happening?
type不生效

### Environment Info 

```shell
https://codesandbox.io/s/nervous-murdock-9y35xr?file=/src/Demo.vue
```

### PR DESCRIPTION
**Pull request by liuzaijiang**
fix #913

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [x] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

File: packages/components/modal/demo/Async.vue [hunk 1]
```diff
@@ -1,27 +1,22 @@
 <template>
-  <IxSpace>
-    <IxButton @click="visible = !visible">Change visible</IxButton>
-    <IxButton mode="primary" @click="openModal">Open modal</IxButton>
-  </IxSpace>
-  <IxModal v-model:visible="visible" title="This is title" type="confirm" @ok="onOk">
-    <p>Some contents...</p>
+  <IxButton mode="primary" @click="showModal">Open Modal with async logic</IxButton>
+  <IxModal v-model:visible="visible" title="标题" type="confirm" :onOk="onOk">
+    <p>内容文本...</p>
```
Comment (danranVm) [inline packages/components/modal/demo/Async.vue:4]:
```suggestion
  <IxModal v-model:visible="visible" title="This is title" type="confirm" @ok="onOk">
    <p>Some contents..</p>
```
要么就全中文嘛，按钮是英文，弹窗是中文，好奇怪。 还有 `:onOk` => `@ok`

**Review by danranVm — CHANGES_REQUESTED** [review]
