### PR TITLE
fix(comp:affix): fix the problem of dynamic display

### LINKED ISSUE #849: [comp:anchor] anchor 组件使用 v-show时组件宽高计算有误
- [x] I have searched the [issues](https://github.com/IDuxFE/idux/issues) of this repository and believe that this is not a duplicate.
          
### Reproduction link
[https://codesandbox.io/s/romantic-black-73r6wm?file=/src/App.vue](https://codesandbox.io/s/romantic-black-73r6wm?file=/src/App.vue)

### Steps to reproduce
见重现连接

### What is expected?
1. anchor 组件使用 v-show时组件宽高计算正常
2. 使用v-if时位置计算正常

### What is actually happening?
1. anchor 组件使用 v-show时组件宽高计算有误
2. 使用v-if时只有页面重绘才会计算位置

### Environment Info 

```shell
见重现连接
```

### PR DESCRIPTION
**Pull request by jackson-yyy**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/IDuxFE/idux/blob/main/packages/site/src/docs/Contributing.zh.md#commit)
- [ ] Tests for the changes have been added/updated or not needed
- [ ] Docs and demo have been added/updated or not needed

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Component style update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

#849

## What is the new behavior?
1. styles only appear when sticky is triggered 
2. provide  a method to update affix styles manually

## Other information
fix #849

### CODE REVIEW

File: packages/components/anchor/src/Anchor.tsx [hunk 1]
```diff
@@ -36,6 +36,14 @@ export default defineComponent({
     const { activeLink } = useLinks(props, config)
     const { anchorRef, inkBallElRef, inkBallClasses, inkBallTop } = useInkBall(activeLink, mergedPrefixCls)
 
+    const affixRef = ref<typeof IxAffix | null>(null)
```
Comment (danranVm) [inline packages/components/anchor/src/Anchor.tsx:39]:
```suggestion
    const affixRef = ref<AffixInstance | null>(null)
```

记得给 AffixInstance 加一个 update 的 bindings

**Review by danranVm — APPROVED** [review]

**Review by danranVm — APPROVED** [review]
